miura chapter-3
OnizukaLab/100knock pull request #31
Opened 2018-05-15 07:24 UTC by bmiura

3章の20-29をしました。よろしくお願いします。

2018-05-15 08:30 UTC, NomotoEriko requested changes
@bmiura コメントしました．コメントについてなんかあればまた言ってください．

2018-05-15 08:30 UTC, NomotoEriko commented on 2018/miura/chapter3/q_20.py
> +			article = json.loads(line)
`article = json.loads(line.decode("utf-8"))`
なんかbite型入れんなエラーが出たので

2018-05-15 08:30 UTC, NomotoEriko commented on 2018/miura/chapter3/q_20.py
> +	with gzip.open('../../../data/jawiki-country.json.gz', mode='r') as f:
`for line in gzip.open('../../../data/jawiki-country.json.gz', mode='r'):`
こう書けるで．

2018-05-15 08:30 UTC, NomotoEriko commented on 2018/miura/chapter3/q_23.py
> +		print(line.strip('='), line.count('=')//2)
`=== aaa==aaa ===`
`== aaa ====`
みたいな表記があった時にダメになりそー気になるー
```
m = re.match('^(==+).*?(==+)$', line)
if m:
	f = len(m.group(1))
	l = len(m.group(2))
	print(line.strip('='), min(f, l))
```
これやわ

2018-05-15 16:42 UTC, bmiura commented on 2018/miura/chapter3/q_23.py
> +		print(line.strip('='), line.count('=')//2)
ぱっと見データになかったので雑に処理してしまいました…すいません…
?って{0,1}以外の役割もあったんですね。勉強になりました。ありがとうございます。

2018-05-15 17:24 UTC, bmiura commented on 2018/miura/chapter3/q_20.py
> +	with gzip.open('../../../data/jawiki-country.json.gz', mode='r') as f:
withを使うとブロック抜けたときに勝手にclose()してくれるらしいです。
別にこれぐらいだったらGCにお任せしても何も問題ないだろうという気持ちもあります。

2018-05-15 17:29 UTC, bmiura commented
修正しました。

2018-05-16 00:49 UTC, NomotoEriko commented on 2018/miura/chapter3/q_20.py
> +	with gzip.open('../../../data/jawiki-country.json.gz', mode='r') as f:
なるほど．勉強になりました．

2018-05-16 00:49 UTC, NomotoEriko approved these changes

2018-05-16 00:50 UTC, merged