miura chapter-4
OnizukaLab/100knock pull request #35
Opened 2018-05-17 21:49 UTC by bmiura

4章をしました。よろしくお願いします。
#33

2018-05-18 06:12 UTC, NomotoEriko commented
neko.txt.mecab をSlackかなんかでくださいな．

2018-05-18 06:12 UTC, NomotoEriko commented
@bmiura neko.txt.mecab をSlackかなんかでくださいな．

2018-05-23 04:17 UTC, NomotoEriko commented
@bmiura ひとまず挙動だけ見ました．q39，問題には両対数グラフかけって言われてるけど，片対数グラフになってるで．

2018-05-23 05:19 UTC, NomotoEriko requested changes
q39 のグラフ描画を両対数グラフにしてもらえればokです．

2018-05-23 21:30 UTC, bmiura commented
ありがとうございます。両対数グラフにしました。

2018-05-24 01:36 UTC, merged